---
title: "Lab01"
author: "Finn Lindgren"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Lab01}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Statistical computing MATH10093: Computer lab 1

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
solutions <- FALSE
knitr::opts_chunk$set(
  fig.path = "figure/lab01-",
  fig.align = "center",
  fig.show = "hold",
  size = "small"#,
#  fig.width = 8,
#  fig.height = 5.2,
#  out.width = "\\linewidth",
#  out.height = "0.65\\linewidth"
)
set.seed(12345L)
library(ggplot2)
theme_set(theme_bw())
library(StatCompLab)
```

In this lab session you'll gradually develop R code for estimating multiple linear models, and plotting the results. You will not hand in anything, but you should keep your code script file for later use.

## Startup

### Regular startup on rstudio.cloud

1. If you haven't already done so, go to the technical setup page on Learn
  and follow the links to sign up to [rstudio.cloud](https://rstudio.cloud)
2. In rstudio.cloud, go to the "Statistical Computing" Workspace (in the left side menu)
3. Create a new project. Click on the project name at the top of the window to rename it to a descriptive name, for example `Lab01`.
4. In the project `Console` window, run `devtools::install_github("finnlindgren/StatCompLab")`
4. Go to the Learn page and open the \code{Lecture01.pdf} lecture notes so you can refer to them easily during the lab. Read through the pages on formulas and functions before you continue with lab.

### Alternative local computer RStudio

1. If you've followed the links on the Learn page about technical setup and installed R and RStudio, you have the option of running RStudio on your own computer.
2. Choose a folder/location on your file system in which to store your course files,
and in RStudio, create a new Project (File$\rightarrow$New~Project$\rightarrow$New~Directory$\rightarrow$New Project)
Make sure you choose a location where no part of the path contains any blank spaces, since that can sometimes cause problems.  Name the folder `Lab01`, for example.
3.
Next time you want to work on the course files, use
\code{File$\rightarrow$Open~Project} instead (or, if your system has linked .Rproj files to RStudio, you can open RStudio by opening the .Rproj file in the project folder)
4. In the RStudio `Console` window, run `devtools::install_github("finnlindgren/StatCompLab")`
4. Go to the Learn page and open the \code{Lecture01.pdf} lecture notes so you can refer to them easily during the lab. Read through the pages on formulas and functions before you continue with lab.

### Some useful menu options, buttons, and keyboard shortcuts:

* Configuring code syntax diagnostics:
  
  Tools$\rightarrow$Global~Options$\rightarrow$Code$\rightarrow$Diagnostics
  
  This allows you to turn on margin notes that automatically alert you to potential code problems.
* Run the current line of code (or a selected section of code) and step to the next line:

  Press the `Run` button in the top right corner of the editor window, or
  Press `Ctrl+Enter`
* Run all the code in the current script file:

  Press the `Source` button in the top right corner of the editor window, or
  Press `Ctrl+Shift+S`, or
  Press `Ctrl+Shift+Enter`

  Note: the first two options disable the normal automatic value printing; you'll only see the ouput that is explicitly fed into `print()`. The third option displays both the code and the results in the Console window.
* The `styler` package (should already be available on `rstudio.cloud`. Use `install.packages("styler")` in R if you're running on a local installation).
  This will enable options to reformat your script code to (usually) more readable code, by pressing the `Addins` button below the main program menu and choosing e.g. `Style active file`.

### First steps

1. Create a new R script file:
File$\rightarrow$New~File$\rightarrow$R~Script
2. Save the new R script file:
  File$\rightarrow$Save, or
  Press `Ctrl+S`,
  and choose a descriptive filename (e.g. `lab_1_code.R`)

During the lab, remember to save the script file regularly, to avoid losing any work (on both rstudio.cloud and regular RStudio, unsaved changes may still be remembered by the system, but it is much safer to explicitly save the files, and this will also be essential when we start `git` for version control).

3. Now switch to the `Tutorial01` tutorial, either in the `Tutorials` pane (look for the `StatCompLab` package in the list of tutorials)
